import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Navbar } from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen h-[100vh]`}
      >
        <Navbar />
        <div className="flex flex-1 overflow-y-hidden min-h-0">
          <aside className="hidden md:block w-[250px] flex-shrink-0 overflow-y-auto">
            <Sidebar />
          </aside>
          <main className="flex-1 overflow-y-auto p-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
